name: Deploy Admin (Template)

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: Commit to deploy
        required: true
      environment:
        description: Target environment (e.g. production, staging)
        required: true

permissions:
  contents: read

jobs:
  deploy:
    name: Upload Admin Panel
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit_sha }}

      - name: Show template instructions
        run: |
          echo "Template workflow – replace with production-ready deployment commands."
          echo ""
          echo "Recommended steps:"
          echo "1. pnpm --filter frontend build"
          echo "2. rsync standalone output for the admin panel to mydevil"
          echo "3. devil www restart <admin-app>"
          echo ""
          echo "Required secrets before enabling:"
          echo "- MYDEVIL_SSH_HOST / MYDEVIL_SSH_USER / MYDEVIL_SSH_KEY"
          echo "- MYDEVIL_ADMIN_PATH"
